---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']

ignore: |
  web/node_modules/
  .git/
  .cache/
  .pytest_cache/
  __pycache__/
  *.pyc
  *.pyo
  *.egg-info/
  dist/
  build/
