// This file is auto-generated by Supabase
// Do not edit this file directly

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      articles: {
        Row: {
          id: string
          created_at: string | null
          updated_at: string | null
          title: string
          content: string | null
          summary: string | null
          status: 'draft' | 'published' | 'archived'
          user_id: string
          author_id: string | null
          sport: string | null
          league: string | null
          tags: string[] | null
          seo_keywords: string[] | null
          reading_time_minutes: number | null
          published_at: string | null
          featured_image_url: string | null
          game_id: string | null
          byline: string | null
        }
        Insert: {
          id?: string
          created_at?: string | null
          updated_at?: string | null
          title: string
          content?: string | null
          summary?: string | null
          status?: 'draft' | 'published' | 'archived'
          user_id: string
          author_id?: string | null
          sport?: string | null
          league?: string | null
          tags?: string[] | null
          seo_keywords?: string[] | null
          reading_time_minutes?: number | null
          published_at?: string | null
          featured_image_url?: string | null
          game_id?: string | null
          byline?: string | null
        }
        Update: {
          id?: string
          created_at?: string | null
          updated_at?: string | null
          title?: string
          content?: string | null
          summary?: string | null
          status?: 'draft' | 'published' | 'archived'
          user_id?: string
          author_id?: string | null
          sport?: string | null
          league?: string | null
          tags?: string[] | null
          seo_keywords?: string[] | null
          reading_time_minutes?: number | null
          published_at?: string | null
          featured_image_url?: string | null
          game_id?: string | null
          byline?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export type Article = Database['public']['Tables']['articles']['Row'];
